services:
  user-api:
    build: 
      context: .
      dockerfile: 
        TicketEngine.UserApi/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MongoSettings__ConnectionURI=${MONGOSETTINGS_CONNECTIONURI}
      - MongoSettings__DatabaseName=${MONGOSETTINGS_DATABASENAME}
      - JwtSettings__SecretKey=${JWTSETTINGS_SECRETKEY}